import { dropdownItem, TTagsListData } from "../../types/types";

export const PLATFORM_DATA: dropdownItem[] = [
  { name: "All platform", dataAtr: "all", id: "platformSelected" },
  { name: "PC (Windows)", dataAtr: "pc", id: "platformSelected" },
  { name: "web browser", dataAtr: "browser", id: "platformSelected" },
];

export const SORT_DATA: dropdownItem[] = [
  { name: "relevance", dataAtr: "relevance", id: "sortBy" },
  { name: "popularity", dataAtr: "popularity", id: "sortBy" },
  { name: "release date", dataAtr: "release-date", id: "sortBy" },
  { name: "alphabetical", dataAtr: "alphabetical", id: "sortBy" },
];

export const TAGS_LIST_DATA: TTagsListData = [
  "mmorpg",
  "shooter",
  "strategy",
  "moba",
  "racing",
  "sports",
  "social",
  "sandbox",
  "open-world",
  "survival",
  "pvp",
  "pve",
  "pixel",
  "voxel",
  "zombie",
  "turn-based",
  "first-person",
  "third-Person",
  "top-down",
  "tank",
  "space",
  "sailing",
  "side-scroller",
  "superhero",
  "permadeath",
  "card",
  "battle-royale",
  "mmo",
  "mmofps",
  "mmotps",
  "3d",
  "2d",
  "anime",
  "fantasy",
  "sci-fi",
  "fighting",
  "action-rpg",
  "action",
  "military",
  "martial-arts",
  "flight",
  "low-spec",
  "tower-defense",
  "horror",
  "mmorts",
];
